---
delegatebot:
  watch:
  - target: { channel: &pcf-windows C05666253 }
  - target: { channel: &bosh-windows-bots G7MMA3VV0 }
  delegate: &interrupts
    if:
      when:
        - or:
          - and:
            - hours: { tz: America/New_York, start: 09:00, end: 18:00 }
            - day: { tz: America/New_York, days: [ Mon, Tue, Wed, Thu, Fri ] }
            - not: { date: { tz: America/New_York, dates: [ 2019-01-01, 2019-01-21, 2019-02-18, 2019-05-27, 2019-07-04, 2019-09-02, 2019-11-28, 2019-11-29, 2019-12-25 ] } }
          - and:
            - hours: { tz: America/Toronto, start: 09:00, end: 18:00 }
            - day: { tz: America/Toronto, days: [ Mon, Tue, Wed, Thu, Fri ] }
            - not: { date: { tz: America/Toronto, dates: [ 2019-01-01, 2019-02-18, 2019-04-19, 2019-05-20, 2019-07-01, 2019-08-05, 2019-09-02, 2019-10-14, 2019-12-25, 2019-12-26 ] } }
      then:
        union:
          - literalmap:
              from:
                pairist:
                  team: boshwindows
                  role: Interrupt
              users:
                Garima Sharma: U2LAQS9RQ
                Simon Jones: U0H6HC71B
                George Gelashvili: U0FA4167Q
                Matthew Horan: U0563PD3X
                Jackson Feeny: U7U1BRTR8
                Tal Usvyatsky: UL5DFJS4C
                Daniel Basner: UJRBWR9FE
          - user: { id: &Kartik_Lunkad U0MJ7N77U }
  options:
    empty_message: Sorry, no interrupt is available right now. The community may be able to help, or feel free to ping again later.
