---
delegatebot:
  watch:
  - target: { channel: &pcf-windows-eng G0GQ8KXLZ }
  delegate:
    union:
    - user: { id: &Yael UCKDV7ZEK }
    - user: { id: &Natalie U2SSN6RQQ }
    - user: { id: &Yechiel UDT3Q8KLH }
    - user: { id: &Arjun UBKBNQBBM }
    - user: { id: &Matt U0563PD3X }
    - user: { id: &Genevieve U0BSZH3EX }
    - user: { id: &Sophie UF53HEMMW }
    - user: { id: &JRO U5EJ9E8DQ }
    - user: { id: &Cara UK06QV0BU }
